export const airports = [
  ['TLV','Ben Gurion Airport','Tel Aviv','Israel'],
  ['DXB','Dubai International Airport','Dubai','UAE'],
  ['IST','Istanbul Airport','Istanbul','Turkey'],
  ['CAI','Cairo International Airport','Cairo','Egypt'],
  ['AMM','Queen Alia International Airport','Amman','Jordan'],
  ['LHR','Heathrow Airport','London','UK'],
  ['CDG','Charles de Gaulle Airport','Paris','France'],
  ['JED','King Abdulaziz International Airport','Jeddah','Saudi Arabia'],
  ['RUH','King Khalid International Airport','Riyadh','Saudi Arabia'],
  ['DOH','Hamad International Airport','Doha','Qatar'],
  ['CMN','Mohammed V International Airport','Casablanca','Morocco'],
  ['FCO','Leonardo da Vinci Fiumicino Airport','Rome','Italy'],
  ['BCN','Barcelona-El Prat Airport','Barcelona','Spain'],
  ['ATH','Athens International Airport','Athens','Greece'],
  ['BKK','Suvarnabhumi Airport','Bangkok','Thailand'],
  ['KUL','Kuala Lumpur International Airport','Kuala Lumpur','Malaysia'],
  ['MUC','Munich Airport','Munich','Germany'],
  ['AYT','Antalya Airport','Antalya','Turkey'],
  ['VIE','Vienna International Airport','Vienna','Austria'],
  ['ZRH','Zurich Airport','Zurich','Switzerland'],
  ['MAD','Adolfo Suarez Madrid-Barajas Airport','Madrid','Spain'],
  ['AMS','Amsterdam Airport Schiphol','Amsterdam','Netherlands'],
  ['BRU','Brussels Airport','Brussels','Belgium'],
  ['CPH','Copenhagen Airport','Copenhagen','Denmark'],
  ['ARN','Stockholm Arlanda Airport','Stockholm','Sweden'],
  ['HEL','Helsinki-Vantaa Airport','Helsinki','Finland'],
  ['WAW','Warsaw Chopin Airport','Warsaw','Poland'],
  ['PRG','Vaclav Havel Airport Prague','Prague','Czech Republic'],
  ['BUD','Budapest Ferenc Liszt Airport','Budapest','Hungary'],
  ['OTP','Henri Coanda International Airport','Bucharest','Romania'],
  ['SOF','Sofia Airport','Sofia','Bulgaria'],
  ['AUH','Abu Dhabi International Airport','Abu Dhabi','UAE'],
  ['BAH','Bahrain International Airport','Manama','Bahrain'],
  ['KWI','Kuwait International Airport','Kuwait City','Kuwait'],
  ['MCT','Muscat International Airport','Muscat','Oman'],
  ['BEY','Beirut Rafic Hariri Airport','Beirut','Lebanon'],
  ['TUN','Tunis-Carthage Airport','Tunis','Tunisia'],
  ['ALG','Houari Boumediene Airport','Algiers','Algeria'],
  ['JFK','John F Kennedy International Airport','New York','USA'],
  ['LAX','Los Angeles International Airport','Los Angeles','USA'],
  ['ORD','O\'Hare International Airport','Chicago','USA'],
  ['MIA','Miami International Airport','Miami','USA'],
  ['YYZ','Toronto Pearson International Airport','Toronto','Canada'],
  ['YUL','Montreal-Trudeau Airport','Montreal','Canada'],
  ['SIN','Singapore Changi Airport','Singapore','Singapore'],
  ['HKG','Hong Kong International Airport','Hong Kong','Hong Kong'],
  ['ICN','Incheon International Airport','Seoul','South Korea'],
  ['NRT','Narita International Airport','Tokyo','Japan'],
  ['HND','Haneda Airport','Tokyo','Japan'],
  ['PEK','Beijing Capital Airport','Beijing','China'],
  ['PVG','Shanghai Pudong Airport','Shanghai','China'],
  ['DEL','Indira Gandhi International Airport','New Delhi','India'],
  ['BOM','Chhatrapati Shivaji Airport','Mumbai','India'],
  ['MLE','Velana International Airport','Male','Maldives'],
  ['SYD','Sydney Kingsford Smith Airport','Sydney','Australia'],
  ['MEL','Melbourne Airport','Melbourne','Australia'],
  ['AKL','Auckland Airport','Auckland','New Zealand'],
  ['CGK','Soekarno-Hatta Airport','Jakarta','Indonesia'],
  ['DPS','Ngurah Rai Airport','Bali','Indonesia'],
  ['MNL','Ninoy Aquino Airport','Manila','Philippines'],
  ['SGN','Tan Son Nhat Airport','Ho Chi Minh City','Vietnam'],
  ['HAN','Noi Bai Airport','Hanoi','Vietnam'],
  ['DAC','Hazrat Shahjalal Airport','Dhaka','Bangladesh'],
  ['KTM','Tribhuvan Airport','Kathmandu','Nepal'],
  ['TBS','Tbilisi International Airport','Tbilisi','Georgia'],
  ['EVN','Zvartnots Airport','Yerevan','Armenia'],
  ['GYD','Heydar Aliyev Airport','Baku','Azerbaijan'],
  ['LCA','Larnaca International Airport','Larnaca','Cyprus'],
  ['MLA','Malta International Airport','Valletta','Malta'],
  ['NBO','Jomo Kenyatta International Airport','Nairobi','Kenya'],
  ['ADD','Addis Ababa Bole Airport','Addis Ababa','Ethiopia'],
  ['JNB','OR Tambo International Airport','Johannesburg','South Africa'],
  ['CPT','Cape Town International Airport','Cape Town','South Africa'],
  ['MRU','Sir Seewoosagur Ramgoolam Airport','Port Louis','Mauritius'],
  ['SEZ','Seychelles International Airport','Mahe','Seychelles'],
  ['DAR','Julius Nyerere Airport','Dar es Salaam','Tanzania'],
  ['ZNZ','Abeid Amani Karume Airport','Zanzibar','Tanzania'],
  ['LOS','Murtala Muhammed Airport','Lagos','Nigeria'],
  ['ACC','Kotoka International Airport','Accra','Ghana'],
  ['RAK','Marrakech Menara Airport','Marrakech','Morocco'],
  ['SSH','Sharm El Sheikh Airport','Sharm El Sheikh','Egypt'],
  ['HRG','Hurghada International Airport','Hurghada','Egypt'],
  ['LXR','Luxor International Airport','Luxor','Egypt'],
  ['MED','Prince Mohammad bin Abdulaziz Airport','Madinah','Saudi Arabia'],
  ['DMM','King Fahd International Airport','Dammam','Saudi Arabia'],
  ['SHJ','Sharjah International Airport','Sharjah','UAE'],
  ['KHI','Jinnah International Airport','Karachi','Pakistan'],
  ['LHE','Allama Iqbal Airport','Lahore','Pakistan'],
  ['ISB','Islamabad International Airport','Islamabad','Pakistan'],
  ['IKA','Imam Khomeini International Airport','Tehran','Iran'],
  ['MHD','Mashhad International Airport','Mashhad','Iran'],
  ['SYZ','Shiraz International Airport','Shiraz','Iran'],
  ['TAS','Islam Karimov Airport','Tashkent','Uzbekistan'],
  ['ALA','Almaty International Airport','Almaty','Kazakhstan'],
  ['NQZ','Nursultan Nazarbayev Airport','Astana','Kazakhstan'],
  ['ULN','Chinggis Khaan Airport','Ulaanbaatar','Mongolia'],
  ['WNZ','Wenzhou Airport','Wenzhou','China'],
  ['CEB','Mactan-Cebu Airport','Cebu','Philippines'],
  ['DVO','Francisco Bangoy Airport','Davao','Philippines'],
  ['TPE','Taiwan Taoyuan Airport','Taipei','Taiwan'],
  ['KIX','Kansai International Airport','Osaka','Japan'],
  ['CTS','New Chitose Airport','Sapporo','Japan'],
  ['FUK','Fukuoka Airport','Fukuoka','Japan'],
  ['PUS','Gimhae International Airport','Busan','South Korea'],
  ['CJU','Jeju International Airport','Jeju','South Korea'],
  ['PER','Perth Airport','Perth','Australia'],
  ['BNE','Brisbane Airport','Brisbane','Australia'],
  ['ADL','Adelaide Airport','Adelaide','Australia'],
  ['CNS','Cairns Airport','Cairns','Australia'],
  ['CHC','Christchurch Airport','Christchurch','New Zealand'],
  ['WLG','Wellington Airport','Wellington','New Zealand'],
  ['NAN','Nadi International Airport','Nadi','Fiji'],
  ['PPT','Faaa International Airport','Papeete','French Polynesia'],
  ['HNL','Honolulu International Airport','Honolulu','USA'],
  ['SFO','San Francisco International Airport','San Francisco','USA'],
  ['SEA','Seattle-Tacoma Airport','Seattle','USA'],
  ['BOS','Logan International Airport','Boston','USA'],
  ['ATL','Hartsfield-Jackson Airport','Atlanta','USA'],
  ['IAD','Washington Dulles Airport','Washington','USA'],
  ['LAS','Harry Reid Airport','Las Vegas','USA'],
  ['MCO','Orlando International Airport','Orlando','USA'],
  ['MEX','Mexico City Airport','Mexico City','Mexico'],
  ['CUN','Cancun International Airport','Cancun','Mexico'],
  ['BOG','El Dorado Airport','Bogota','Colombia'],
  ['LIM','Jorge Chavez Airport','Lima','Peru'],
  ['SCL','Arturo Merino Benitez Airport','Santiago','Chile'],
  ['GRU','Sao Paulo-Guarulhos Airport','Sao Paulo','Brazil'],
  ['EZE','Ministro Pistarini Airport','Buenos Aires','Argentina'],
  ['PUJ','Punta Cana Airport','Punta Cana','Dominican Republic'],
  ['MBJ','Sangster Airport','Montego Bay','Jamaica'],
  ['YVR','Vancouver International Airport','Vancouver','Canada'],
  ['YYC','Calgary International Airport','Calgary','Canada'],
  ['YOW','Ottawa International Airport','Ottawa','Canada'],
  ['YQB','Quebec City Airport','Quebec City','Canada'],
];
